# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Unique invoice identifier (e.g., INV-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        help_text="Date the invoice was issued",
                        verbose_name="Issue Date",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Payment due date", verbose_name="Due Date"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all line items",
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax rate as percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated tax amount",
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount applied to invoice",
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount due",
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount paid so far",
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used",
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference or transaction ID",
                        max_length=255,
                        verbose_name="Payment Reference",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invoice was fully paid",
                        null=True,
                        verbose_name="Paid At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for the client",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        help_text="Payment terms and conditions",
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF invoice",
                        null=True,
                        upload_to="invoices/pdfs/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe invoice ID for payment tracking",
                        max_length=255,
                        verbose_name="Stripe Invoice ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe payment intent ID",
                        max_length=255,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invoice was sent to the client",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the client first viewed the invoice",
                        null=True,
                        verbose_name="Viewed At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client being invoiced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contract (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the item or service",
                        verbose_name="Description",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Quantity of items",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount (quantity × unit_price)",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order of the item",
                        verbose_name="Order",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoicing_i_invoice_f2b05e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client"], name="invoicing_i_client__488c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["contract"], name="invoicing_i_contrac_62be36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoicing_i_status_2eeee5_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issue_date", "due_date"], name="invoicing_i_issue_d_2ce6ab_idx"
            ),
        ),
    ]
