# Generated by Django 5.1.4 on 2025-12-27 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(help_text='Unique contract identifier (e.g., CNT-001)', max_length=50, unique=True, verbose_name='Contract Number')),
                ('title', models.CharField(help_text='Brief title describing the contract', max_length=255, verbose_name='Contract Title')),
                ('description', models.TextField(help_text='Detailed description of the contract scope', verbose_name='Description')),
                ('contract_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('hourly', 'Hourly'), ('retainer', 'Retainer'), ('milestone', 'Milestone-based')], default='fixed_price', max_length=20, verbose_name='Contract Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(help_text='Contract start date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (if applicable)', null=True, verbose_name='End Date')),
                ('value', models.DecimalField(decimal_places=2, help_text='Total contract value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Contract Value')),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3, verbose_name='Currency')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (for hourly contracts)', max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours (for hourly contracts)', max_digits=8, null=True, verbose_name='Estimated Hours')),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and conditions (e.g., "Net 30", "50% upfront")', verbose_name='Payment Terms')),
                ('invoice_schedule', models.CharField(blank=True, help_text='When to generate invoices (e.g., "Monthly", "Upon milestone completion")', max_length=50, verbose_name='Invoice Schedule')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Full contract terms and conditions', verbose_name='Terms and Conditions')),
                ('signed_at', models.DateTimeField(blank=True, help_text='When the contract was signed', null=True, verbose_name='Signed At')),
                ('signed_by_client', models.BooleanField(default=False, help_text='Whether the client has signed the contract', verbose_name='Signed by Client')),
                ('signed_by_company', models.BooleanField(default=False, help_text='Whether the company has signed the contract', verbose_name='Signed by Company')),
                ('signature_client', models.TextField(blank=True, help_text='Client digital signature or e-signature ID', verbose_name='Client Signature')),
                ('signature_company', models.TextField(blank=True, help_text='Company digital signature or e-signature ID', verbose_name='Company Signature')),
                ('contract_file', models.FileField(blank=True, help_text='PDF or document file of the contract', null=True, upload_to='contracts/files/', verbose_name='Contract File')),
                ('docusign_envelope_id', models.CharField(blank=True, help_text='DocuSign envelope ID for e-signature tracking', max_length=255, verbose_name='DocuSign Envelope ID')),
                ('invoiced_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount invoiced for this contract', max_digits=12, verbose_name='Invoiced Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid for this contract', max_digits=12, verbose_name='Paid Amount')),
                ('completion_percentage', models.IntegerField(default=0, help_text='Overall contract completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Completion %')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the contract', verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format', verbose_name='Metadata')),
                ('client', models.ForeignKey(help_text='Client this contract is with', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, help_text='Team member responsible for this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title describing the milestone', max_length=255, verbose_name='Milestone Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of milestone deliverables', verbose_name='Description')),
                ('due_date', models.DateField(help_text='Expected completion date', verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount for this milestone', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Milestone Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the milestone was completed', null=True, verbose_name='Completed At')),
                ('invoice_generated', models.BooleanField(default=False, help_text='Whether an invoice has been generated for this milestone', verbose_name='Invoice Generated')),
                ('order', models.IntegerField(default=0, help_text='Display order of the milestone', verbose_name='Order')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverables for this milestone', verbose_name='Deliverables')),
                ('notes', models.TextField(blank=True, help_text='Notes about the milestone', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who marked the milestone as complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(help_text='Contract this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Milestone',
                'verbose_name_plural': 'Contract Milestones',
                'ordering': ['order', 'due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_c_contrac_18f6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client'], name='contracts_c_client__2cfe0d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_c_status_bd0fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_e74c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['owner'], name='contracts_c_owner_i_09c72a_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['contract', 'status'], name='contracts_c_contrac_f2aebc_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['due_date'], name='contracts_c_due_dat_20caa3_idx'),
        ),
    ]
