# Generated by Django 5.1.4 on 2025-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_contrac_876f48_idx',
            old_name='contracts_c_contrac_18f6c0_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_client__6ebd28_idx',
            old_name='contracts_c_client__2cfe0d_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_status_aa7a80_idx',
            old_name='contracts_c_status_bd0fd8_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_start_d_f953e0_idx',
            old_name='contracts_c_start_d_e74c5a_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_c_owner_i_6a8def_idx',
            old_name='contracts_c_owner_i_09c72a_idx',
        ),
        migrations.RenameIndex(
            model_name='contractmilestone',
            new_name='contracts_c_contrac_f4dd37_idx',
            old_name='contracts_c_contrac_f2aebc_idx',
        ),
        migrations.RenameIndex(
            model_name='contractmilestone',
            new_name='contracts_c_due_dat_af75dd_idx',
            old_name='contracts_c_due_dat_20caa3_idx',
        ),
    ]
