# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address for authentication",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin - Full Access"),
                            ("manager", "Manager - Manage Contracts & Invoices"),
                            ("contributor", "Contributor - Limited Access"),
                            ("client", "Client - Portal Access Only"),
                        ],
                        default="contributor",
                        help_text="User role within the organization",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="User full name",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="User job title or position",
                        max_length=100,
                        verbose_name="Job Title",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User preferred timezone",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Preferred language code",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications",
                        verbose_name="Email Notifications",
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Receive SMS notifications",
                        verbose_name="SMS Notifications",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable 2FA for enhanced security",
                        verbose_name="Two-Factor Authentication",
                    ),
                ),
                (
                    "two_factor_secret",
                    models.CharField(
                        blank=True,
                        help_text="TOTP secret key for 2FA",
                        max_length=32,
                        verbose_name="2FA Secret Key",
                    ),
                ),
                (
                    "two_factor_backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Backup codes for 2FA recovery",
                        verbose_name="2FA Backup Codes",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of last login",
                        null=True,
                        verbose_name="Last Login IP",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email has been verified",
                        verbose_name="Email Verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When email was verified",
                        null=True,
                        verbose_name="Verified At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional user metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this API key",
                        max_length=100,
                        verbose_name="Key Name",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The actual API key (hashed)",
                        max_length=255,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="First few characters of key for identification",
                        max_length=10,
                        verbose_name="Key Prefix",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="List of allowed API scopes/permissions",
                        verbose_name="Scopes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the API key is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the key was last used",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the key has been used",
                        verbose_name="Usage Count",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send invitation to",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin - Full Access"),
                            ("manager", "Manager - Manage Contracts & Invoices"),
                            ("contributor", "Contributor - Limited Access"),
                            ("client", "Client - Portal Access Only"),
                        ],
                        default="contributor",
                        help_text="Role to assign upon acceptance",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "invitation_token",
                    models.CharField(
                        help_text="Unique token for invitation link",
                        max_length=255,
                        unique=True,
                        verbose_name="Invitation Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the invitation expires",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Accepted At"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message to include in invitation email",
                        verbose_name="Invitation Message",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Invitation",
                "verbose_name_plural": "User Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key"], name="accounts_ap_key_d955e0_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["is_active"], name="accounts_ap_is_acti_5d74e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinvitation",
            index=models.Index(
                fields=["email", "status"], name="accounts_us_email_39636f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinvitation",
            index=models.Index(
                fields=["invitation_token"], name="accounts_us_invitat_bf594a_idx"
            ),
        ),
    ]
