# Generated by Django 5.1.4 on 2025-12-30 14:41

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tenant_and_related_models'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='accounts_ap_key_d955e0_idx',
            old_name='accounts_ap_key_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='accounts_ap_tenant__02badc_idx',
            old_name='accounts_ap_tenant_m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_06fc52_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_tenant__731b87_idx',
            old_name='accounts_us_tenant__e1f2a3_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_a5841d_idx',
            old_name='accounts_us_is_acti_4ee882_idx',
        ),
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_email_39636f_idx',
            old_name='accounts_us_email_s_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_tenant__e21918_idx',
            old_name='accounts_us_tenant_s_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='userinvitation',
            new_name='accounts_us_invitat_bf594a_idx',
            old_name='accounts_us_invitat_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
