"""
Tests for ai_assistant app URL configuration.

Tests cover:
- Router registration produces correct URLs for all ViewSets
- URL names are correctly generated by DefaultRouter
- Custom action URLs are accessible
"""

import pytest
from django.urls import reverse, resolve


# ============================================================================
# AI Suggestion URL Tests
# ============================================================================

@pytest.mark.django_db
class TestAISuggestionURLs:
    """Tests for AISuggestion URL patterns."""

    def test_ai_suggestion_list_url(self):
        """Test ai-suggestion-list URL resolves correctly."""
        url = reverse('ai_assistant:ai-suggestion-list')
        assert url == '/api/ai/api/ai-suggestions/'

    def test_ai_suggestion_detail_url(self):
        """Test ai-suggestion-detail URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:ai-suggestion-detail', kwargs={'pk': pk})
        assert f'/api/ai/api/ai-suggestions/{pk}/' == url

    def test_ai_suggestion_accept_url(self):
        """Test ai-suggestion-accept URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:ai-suggestion-accept', kwargs={'pk': pk})
        assert f'/api/ai/api/ai-suggestions/{pk}/accept/' == url

    def test_ai_suggestion_dismiss_url(self):
        """Test ai-suggestion-dismiss URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:ai-suggestion-dismiss', kwargs={'pk': pk})
        assert f'/api/ai/api/ai-suggestions/{pk}/dismiss/' == url

    def test_ai_suggestion_generate_url(self):
        """Test ai-suggestion-generate URL resolves correctly."""
        url = reverse('ai_assistant:ai-suggestion-generate')
        assert url == '/api/ai/api/ai-suggestions/generate/'

    def test_ai_suggestion_list_resolves(self):
        """Test that list URL resolves to the correct view."""
        resolver = resolve('/api/ai/api/ai-suggestions/')
        assert resolver.url_name == 'ai-suggestion-list'


# ============================================================================
# Cash Flow Prediction URL Tests
# ============================================================================

@pytest.mark.django_db
class TestCashFlowPredictionURLs:
    """Tests for CashFlowPrediction URL patterns."""

    def test_cash_flow_prediction_list_url(self):
        """Test cash-flow-prediction-list URL resolves correctly."""
        url = reverse('ai_assistant:cash-flow-prediction-list')
        assert url == '/api/ai/api/cash-flow-predictions/'

    def test_cash_flow_prediction_detail_url(self):
        """Test cash-flow-prediction-detail URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:cash-flow-prediction-detail', kwargs={'pk': pk})
        assert f'/api/ai/api/cash-flow-predictions/{pk}/' == url

    def test_cash_flow_prediction_predict_url(self):
        """Test cash-flow-prediction-predict URL resolves correctly."""
        url = reverse('ai_assistant:cash-flow-prediction-predict')
        assert url == '/api/ai/api/cash-flow-predictions/predict/'

    def test_cash_flow_prediction_list_resolves(self):
        """Test that list URL resolves to the correct view."""
        resolver = resolve('/api/ai/api/cash-flow-predictions/')
        assert resolver.url_name == 'cash-flow-prediction-list'


# ============================================================================
# AI Insight URL Tests
# ============================================================================

@pytest.mark.django_db
class TestAIInsightURLs:
    """Tests for AIInsight URL patterns."""

    def test_ai_insight_list_url(self):
        """Test ai-insight-list URL resolves correctly."""
        url = reverse('ai_assistant:ai-insight-list')
        assert url == '/api/ai/api/ai-insights/'

    def test_ai_insight_detail_url(self):
        """Test ai-insight-detail URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:ai-insight-detail', kwargs={'pk': pk})
        assert f'/api/ai/api/ai-insights/{pk}/' == url

    def test_ai_insight_mark_read_url(self):
        """Test ai-insight-mark-read URL resolves correctly."""
        import uuid
        pk = uuid.uuid4()
        url = reverse('ai_assistant:ai-insight-mark-read', kwargs={'pk': pk})
        assert f'/api/ai/api/ai-insights/{pk}/mark-read/' == url

    def test_ai_insight_mark_all_read_url(self):
        """Test ai-insight-mark-all-read URL resolves correctly."""
        url = reverse('ai_assistant:ai-insight-mark-all-read')
        assert url == '/api/ai/api/ai-insights/mark-all-read/'

    def test_ai_insight_list_resolves(self):
        """Test that list URL resolves to the correct view."""
        resolver = resolve('/api/ai/api/ai-insights/')
        assert resolver.url_name == 'ai-insight-list'
