# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("invoicing", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this template",
                        max_length=255,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "Invoice Created"),
                            ("invoice_sent", "Invoice Sent to Client"),
                            ("invoice_paid", "Invoice Paid"),
                            ("invoice_overdue", "Invoice Overdue"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_receipt", "Payment Receipt"),
                            ("contract_signed", "Contract Signed"),
                            ("contract_expiring", "Contract Expiring Soon"),
                            ("client_welcome", "New Client Welcome"),
                            ("reminder_payment_due", "Payment Due Reminder"),
                        ],
                        help_text="Type of notification this template is for",
                        max_length=50,
                        unique=True,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line for email notifications. Supports {{variables}}",
                        max_length=255,
                        verbose_name="Email Subject",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        help_text="Plain text version of the message. Supports {{variables}}",
                        verbose_name="Plain Text Body",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML version of the message. Supports {{variables}}",
                        verbose_name="HTML Body",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "send_to_client",
                    models.BooleanField(
                        default=True,
                        help_text="Send this notification to the client",
                        verbose_name="Send to Client",
                    ),
                ),
                (
                    "send_to_owner",
                    models.BooleanField(
                        default=False,
                        help_text="Send this notification to the contract/invoice owner",
                        verbose_name="Send to Owner",
                    ),
                ),
                (
                    "available_variables",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of available template variables",
                        size=None,
                        verbose_name="Available Variables",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["template_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for notification (if not to a user)",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS notifications",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        help_text="Plain text message content",
                        verbose_name="Message (Plain Text)",
                    ),
                ),
                (
                    "message_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML message content",
                        verbose_name="Message (HTML)",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Failed At"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if delivery failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from email/SMS provider",
                        max_length=255,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "related_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="contracts.contract",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User receiving this notification (if logged in)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used for this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="notificatio_email_8cf883_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_d92267_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                ],
            },
        ),
    ]
