# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this integration",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("quickbooks", "QuickBooks"),
                            ("xero", "Xero"),
                            ("google_calendar", "Google Calendar"),
                            ("outlook", "Microsoft Outlook"),
                            ("slack", "Slack"),
                            ("custom", "Custom Integration"),
                        ],
                        max_length=30,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Service-specific configuration (API keys, endpoints, etc.)",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, verbose_name="Access Token"),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, verbose_name="Refresh Token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token Expires At"
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="Sync Enabled"),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Sync Interval (minutes)"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync"
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Last Sync Status"
                    ),
                ),
                (
                    "last_sync_error",
                    models.TextField(blank=True, verbose_name="Last Sync Error"),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook Secret"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                (
                    "records_synced",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Records Synced"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Errors"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duration (ms)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Sync Log",
                "verbose_name_plural": "Integration Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
