# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposal_number",
                    models.CharField(
                        help_text="Unique proposal identifier (e.g., PRP-00001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Proposal Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the proposal",
                        max_length=255,
                        verbose_name="Proposal Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the proposal",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("converted", "Converted"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        help_text="Proposal expiration date", verbose_name="Valid Until"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total proposal value",
                        max_digits=12,
                        verbose_name="Total Value",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the proposal was sent to the client",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the client first viewed the proposal",
                        null=True,
                        verbose_name="Viewed At",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the client accepted the proposal",
                        null=True,
                        verbose_name="Accepted At",
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the client declined the proposal",
                        null=True,
                        verbose_name="Declined At",
                    ),
                ),
                (
                    "client_message",
                    models.TextField(
                        blank=True,
                        help_text="Message from the client upon acceptance or decline",
                        verbose_name="Client Message",
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Client digital signature or e-signature data",
                        verbose_name="Signature",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF proposal",
                        null=True,
                        upload_to="proposals/pdfs/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this proposal is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contract generated from this proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="contracts.contract",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member responsible for this proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("edited", "Edited"),
                            ("converted", "Converted"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                        verbose_name="Activity Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the activity",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user who performed the activity",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Proposal this activity relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Activity",
                "verbose_name_plural": "Proposal Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalPricingOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the pricing option",
                        max_length=255,
                        verbose_name="Option Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the pricing option",
                        verbose_name="Description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this option",
                        max_digits=12,
                        verbose_name="Price",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the recommended option",
                        verbose_name="Is Recommended",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features included in this option",
                        verbose_name="Features",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order of the pricing option",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Proposal this pricing option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_options",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Pricing Option",
                "verbose_name_plural": "Proposal Pricing Options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProposalSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the section",
                        max_length=255,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Section content", verbose_name="Content"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order of the section",
                        verbose_name="Order",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("scope", "Scope"),
                            ("timeline", "Timeline"),
                            ("pricing", "Pricing"),
                            ("terms", "Terms"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Proposal this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Section",
                "verbose_name_plural": "Proposal Sections",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["proposal_number"], name="proposals_p_proposa_f90f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["client"], name="proposals_p_client__0bb106_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(fields=["status"], name="proposals_p_status_aed14b_idx"),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(fields=["owner"], name="proposals_p_owner_i_106566_idx"),
        ),
    ]
