# Generated by Django 5.1.15 on 2026-02-07 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_remove_client_company_name_required_for_companies_and_more"),
        (
            "contracts",
            "0002_rename_contracts_c_contrac_18f6c0_idx_contracts_c_contrac_876f48_idx_and_more",
        ),
        (
            "invoicing",
            "0002_rename_invoicing_i_invoice_e7b0b8_idx_invoicing_i_invoice_f2b05e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Document description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("proposal", "Proposal"),
                            ("attachment", "Attachment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded document file",
                        upload_to="documents/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="File extension",
                        max_length=20,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Processing Status",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Processing Error"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document is accessible via client portal",
                        verbose_name="Public",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Tags"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_files",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="contracts.contract",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type"], name="documents_d_documen_40c475_idx"
                    ),
                    models.Index(
                        fields=["client"], name="documents_d_client__75b1a2_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="documents_d_uploade_6455fb_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="documents_d_created_71dced_idx"
                    ),
                ],
            },
        ),
    ]
