# Generated by Django 5.1.4 on 2025-12-27 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Invalid schema name. Can only contain lowercase letters, numbers and underscores. Must start with a letter.', regex='^public$')])),
                ('name', models.CharField(help_text='The official name of the organization', max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(help_text='Unique identifier for the tenant (used in subdomain)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')], verbose_name='Slug')),
                ('tenant_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('agency', 'Digital Agency'), ('startup', 'SaaS Startup'), ('enterprise', 'Enterprise')], default='freelancer', max_length=20, verbose_name='Tenant Type')),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter Plan - $19/month'), ('pro', 'Pro Plan - $49/month'), ('business', 'Business Plan - $99/month')], default='free', max_length=20, verbose_name='Subscription Plan')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Active Stripe subscription ID', max_length=255, null=True, verbose_name='Stripe Subscription ID')),
                ('contact_email', models.EmailField(help_text='Primary contact email for the organization', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Contact Phone')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='United States', max_length=100, verbose_name='Country')),
                ('logo', models.ImageField(blank=True, help_text='Company logo for branding', null=True, upload_to='tenants/logos/', verbose_name='Company Logo')),
                ('primary_color', models.CharField(default='#1E40AF', help_text='Hex color code for primary brand color', max_length=7, verbose_name='Primary Brand Color')),
                ('secondary_color', models.CharField(default='#10B981', help_text='Hex color code for secondary/accent color', max_length=7, verbose_name='Secondary Brand Color')),
                ('timezone', models.CharField(default='UTC', help_text='Default timezone for the organization', max_length=50, verbose_name='Timezone')),
                ('currency', models.CharField(default='USD', help_text='ISO currency code (USD, EUR, GBP, etc.)', max_length=3, verbose_name='Default Currency')),
                ('language', models.CharField(default='en', help_text='Default language code', max_length=10, verbose_name='Default Language')),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum number of users allowed for this tenant', verbose_name='Maximum Users')),
                ('max_clients', models.PositiveIntegerField(default=10, help_text='Maximum number of clients allowed', verbose_name='Maximum Clients')),
                ('max_contracts', models.PositiveIntegerField(default=5, help_text='Maximum active contracts allowed', verbose_name='Maximum Contracts')),
                ('max_invoices_per_month', models.PositiveIntegerField(default=10, help_text='Maximum invoices that can be created per month', verbose_name='Max Invoices Per Month')),
                ('enable_api_access', models.BooleanField(default=False, help_text='Allow API access for integrations', verbose_name='Enable API Access')),
                ('enable_custom_branding', models.BooleanField(default=False, help_text='Allow custom branding in client portals', verbose_name='Enable Custom Branding')),
                ('enable_multi_currency', models.BooleanField(default=False, help_text='Support multiple currencies', verbose_name='Enable Multi-Currency')),
                ('enable_advanced_analytics', models.BooleanField(default=False, help_text='Access to advanced analytics and reporting', verbose_name='Enable Advanced Analytics')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is currently active', verbose_name='Active')),
                ('is_trial', models.BooleanField(default=True, help_text='Whether this is a trial account', verbose_name='Trial Account')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends', null=True, verbose_name='Trial End Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary domain for the tenant', verbose_name='Primary Domain')),
                ('ssl_enabled', models.BooleanField(default=True, help_text='Whether SSL/TLS is enabled for this domain', verbose_name='SSL Enabled')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the domain ownership has been verified', verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the domain was verified', null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_ten_slug_71a524_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='tenants_ten_schema__b8e913_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['plan'], name='tenants_ten_plan_e8f0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_a07e38_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain'], name='tenants_dom_domain_0f56d4_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['tenant', 'is_primary'], name='tenants_dom_tenant__1479ea_idx'),
        ),
    ]
