# Generated by Django 5.1.4 on 2025-12-30 14:52

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domain',
            new_name='tenants_dom_domain_6df599_idx',
            old_name='tenants_dom_domain_0f56d4_idx',
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='tenants_dom_tenant__3bd559_idx',
            old_name='tenants_dom_tenant__1479ea_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_ten_slug_63daca_idx',
            old_name='tenants_ten_slug_71a524_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_ten_schema__df93bb_idx',
            old_name='tenants_ten_schema__b8e913_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_ten_plan_2744ca_idx',
            old_name='tenants_ten_plan_e8f0a9_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_ten_is_acti_8f654a_idx',
            old_name='tenants_ten_is_acti_a07e38_idx',
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
