# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique transaction identifier",
                        max_length=255,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        help_text="When the payment was made",
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe payment intent ID",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe charge ID",
                        max_length=255,
                        verbose_name="Stripe Charge ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe customer ID",
                        max_length=255,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of card number",
                        max_length=4,
                        verbose_name="Card Last 4 Digits",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        help_text="Card brand (Visa, Mastercard, etc.)",
                        max_length=20,
                        verbose_name="Card Brand",
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount refunded",
                        max_digits=12,
                        verbose_name="Refunded Amount",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for refund",
                        verbose_name="Refund Reason",
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was refunded",
                        null=True,
                        verbose_name="Refunded At",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code if payment failed",
                        max_length=50,
                        verbose_name="Failure Code",
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if payment failed",
                        verbose_name="Failure Message",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the payment",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to payment receipt",
                        verbose_name="Receipt URL",
                    ),
                ),
                (
                    "receipt_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether receipt was sent to client",
                        verbose_name="Receipt Sent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice"], name="payments_pa_invoice_fcb1dc_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                    models.Index(
                        fields=["payment_method"], name="payments_pa_payment_5c92d7_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payments_pa_stripe__6fe52c_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="payments_pa_payment_1d6e55_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("other", "Other"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default payment method",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Card Last 4 Digits"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Card Brand"
                    ),
                ),
                (
                    "card_exp_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Card Expiration Month"
                    ),
                ),
                (
                    "card_exp_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Card Expiration Year"
                    ),
                ),
                (
                    "stripe_payment_method_id",
                    models.CharField(
                        help_text="Stripe payment method ID",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Payment Method ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this payment method is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who owns this payment method",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "is_default"],
                        name="payments_pa_client__b97322_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_method_id"],
                        name="payments_pa_stripe__ffc15c_idx",
                    ),
                ],
            },
        ),
    ]
