# Generated by Django 5.1.4 on 2025-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_invoice_fcb1dc_idx',
            old_name='payments_pa_invoice_4b5568_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_pa_status_ea9ec2_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_5c92d7_idx',
            old_name='payments_pa_payment_e83158_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_transac_8e9d99_idx',
            old_name='payments_pa_transac_61a40f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_stripe__6fe52c_idx',
            old_name='payments_pa_stripe__cd24e4_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_1d6e55_idx',
            old_name='payments_pa_payment_2ba4f8_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='payments_pa_client__b97322_idx',
            old_name='payments_pa_client__d77e5c_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='payments_pa_stripe__ffc15c_idx',
            old_name='payments_pa_stripe__8d3be6_idx',
        ),
    ]
