# Generated by Django 5.1.4 on 2026-02-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Invoice this payment is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="invoicing.invoice",
            ),
        ),
    ]
