# Generated by Django 5.1.4 on 2025-12-30 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhooks_we_event_t_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhooks_we_source_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhooks_we_status_a53143_idx',
            old_name='webhooks_we_status_idx',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='last_delivery_status',
        ),
        migrations.RemoveField(
            model_name='webhookendpoint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='next_retry_at',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='response_data',
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include in requests', verbose_name='Custom Headers'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful delivery', null=True, verbose_name='Last Success At'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts for failed deliveries', verbose_name='Max Retries'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='retry_delay',
            field=models.PositiveIntegerField(default=60, help_text='Delay between retry attempts in seconds', verbose_name='Retry Delay (seconds)'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='timeout',
            field=models.PositiveIntegerField(default=30, help_text='Request timeout in seconds', verbose_name='Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP headers from the webhook request', verbose_name='Request Headers'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='response_body',
            field=models.JSONField(blank=True, help_text='Response data sent back to webhook source', null=True, verbose_name='Response Body'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='response_code',
            field=models.PositiveIntegerField(blank=True, help_text='HTTP response code sent back', null=True, verbose_name='Response Code'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='event_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='List of event types this endpoint subscribes to', size=None, verbose_name='Subscribed Event Types'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this webhook endpoint is active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, help_text='Total number of webhook deliveries attempted', verbose_name='Total Deliveries'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='url',
            field=models.URLField(help_text='URL where webhook POST requests will be sent', max_length=500, verbose_name='Webhook URL'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(help_text='Unique identifier from the webhook source', max_length=255, unique=True, verbose_name='External Event ID'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(help_text='Type of webhook event (e.g., payment_intent.succeeded)', max_length=255, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the webhook sender', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='payload',
            field=models.JSONField(help_text='Full webhook payload data', verbose_name='Event Payload'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the webhook was successfully processed', null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the webhook was received', verbose_name='Received At'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of processing retry attempts', verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='source',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('custom', 'Custom Webhook')], default='custom', max_length=50, verbose_name='Webhook Source'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed Successfully'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User agent of the webhook request', max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='webhooks_we_event_i_fd6344_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source', 'event_type'], name='webhooks_we_source_5a0d87_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['-received_at'], name='webhooks_we_receive_29580f_idx'),
        ),
    ]
