# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL where webhook POST requests will be sent",
                        max_length=500,
                        verbose_name="Webhook URL",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        help_text="Secret key for HMAC signature verification",
                        max_length=255,
                        verbose_name="Secret Key",
                    ),
                ),
                (
                    "event_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        help_text="List of event types this endpoint subscribes to",
                        size=None,
                        verbose_name="Subscribed Event Types",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this webhook endpoint is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom HTTP headers to include in requests",
                        verbose_name="Custom Headers",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Request timeout in seconds",
                        verbose_name="Timeout (seconds)",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts for failed deliveries",
                        verbose_name="Max Retries",
                    ),
                ),
                (
                    "retry_delay",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Delay between retry attempts in seconds",
                        verbose_name="Retry Delay (seconds)",
                    ),
                ),
                (
                    "total_deliveries",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of webhook deliveries attempted",
                        verbose_name="Total Deliveries",
                    ),
                ),
                (
                    "successful_deliveries",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of successful deliveries",
                        verbose_name="Successful Deliveries",
                    ),
                ),
                (
                    "failed_deliveries",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of failed deliveries",
                        verbose_name="Failed Deliveries",
                    ),
                ),
                (
                    "last_delivery_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last delivery attempt",
                        null=True,
                        verbose_name="Last Delivery At",
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful delivery",
                        null=True,
                        verbose_name="Last Success At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("custom", "Custom Webhook")],
                        default="custom",
                        max_length=50,
                        verbose_name="Webhook Source",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of webhook event (e.g., payment_intent.succeeded)",
                        max_length=255,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Unique identifier from the webhook source",
                        max_length=255,
                        unique=True,
                        verbose_name="External Event ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed Successfully"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Processing Status",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Full webhook payload data",
                        verbose_name="Event Payload",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="HTTP headers from the webhook request",
                        verbose_name="Request Headers",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the webhook was successfully processed",
                        null=True,
                        verbose_name="Processed At",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of processing retry attempts",
                        verbose_name="Retry Count",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts",
                        verbose_name="Max Retries",
                    ),
                ),
                (
                    "response_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="HTTP response code sent back",
                        null=True,
                        verbose_name="Response Code",
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="Response data sent back to webhook source",
                        null=True,
                        verbose_name="Response Body",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the webhook sender",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent of the webhook request",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the webhook was received",
                        verbose_name="Received At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="webhooks_we_event_i_fd6344_idx"
                    ),
                    models.Index(
                        fields=["source", "event_type"],
                        name="webhooks_we_source_5a0d87_idx",
                    ),
                    models.Index(
                        fields=["status"], name="webhooks_we_status_a53143_idx"
                    ),
                    models.Index(
                        fields=["-received_at"], name="webhooks_we_receive_29580f_idx"
                    ),
                ],
            },
        ),
    ]
