# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LateFeePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this late fee policy",
                        max_length=255,
                        verbose_name="Policy Name",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage of Invoice"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="Fee Type",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Flat amount or percentage value",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Fee Amount",
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days after due date before late fees apply",
                        verbose_name="Grace Period (days)",
                    ),
                ),
                (
                    "max_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum fee cap (for percentage fees)",
                        max_digits=12,
                        null=True,
                        verbose_name="Max Fee Amount",
                    ),
                ),
                (
                    "is_compound",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to compound on previous fees",
                        verbose_name="Compound",
                    ),
                ),
                (
                    "apply_frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="once",
                        max_length=20,
                        verbose_name="Apply Frequency",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Late Fee Policy",
                "verbose_name_plural": "Late Fee Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("before_due", "Before Due Date"),
                            ("on_due", "On Due Date"),
                            ("after_due", "After Due Date"),
                        ],
                        default="before_due",
                        max_length=20,
                        verbose_name="Reminder Type",
                    ),
                ),
                (
                    "days_offset",
                    models.IntegerField(
                        default=7,
                        help_text="Days before/after due date to send reminder",
                        verbose_name="Days Offset",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Date the reminder is scheduled to be sent",
                        verbose_name="Scheduled Date",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this reminder is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reminders",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Reminder",
                "verbose_name_plural": "Payment Reminders",
                "ordering": ["scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "status"],
                        name="invoicing_p_invoice_25cd27_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="invoicing_p_schedul_ac97ab_idx"
                    ),
                    models.Index(
                        fields=["status"], name="invoicing_p_status_b39d8c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Descriptive name for this recurring invoice",
                        max_length=255,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="When to start generating invoices",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When to stop generating invoices (optional)",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "next_run_date",
                    models.DateField(
                        help_text="Next date to generate invoice",
                        verbose_name="Next Run Date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Invoice amount per cycle",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "items_template",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Template for invoice line items",
                        verbose_name="Items Template",
                    ),
                ),
                (
                    "auto_send",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically send invoice after generation",
                        verbose_name="Auto Send",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invoices_generated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of invoices generated",
                        verbose_name="Invoices Generated",
                    ),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Generated At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client to invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices",
                        to="contracts.contract",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of this recurring invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Invoice",
                "verbose_name_plural": "Recurring Invoices",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client"], name="invoicing_r_client__64190e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="invoicing_r_status_3f6d83_idx"
                    ),
                    models.Index(
                        fields=["next_run_date"], name="invoicing_r_next_ru_609243_idx"
                    ),
                    models.Index(
                        fields=["frequency"], name="invoicing_r_frequen_d30506_idx"
                    ),
                ],
            },
        ),
    ]
