# Generated by Django 5.1.4 on 2025-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoicing_i_invoice_f2b05e_idx',
            old_name='invoicing_i_invoice_e7b0b8_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoicing_i_client__488c4d_idx',
            old_name='invoicing_i_client__0bf14f_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoicing_i_contrac_62be36_idx',
            old_name='invoicing_i_contrac_42bfa9_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoicing_i_status_2eeee5_idx',
            old_name='invoicing_i_status_af1ec1_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoicing_i_issue_d_2ce6ab_idx',
            old_name='invoicing_i_issue_d_8d8cae_idx',
        ),
    ]
