# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the booking link",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the booking link",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the booking link",
                        verbose_name="Description",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration of each booking in minutes",
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list,
                        help_text="List of available days (1=Monday, 7=Sunday), e.g. [1,2,3,4,5]",
                        verbose_name="Available Days",
                    ),
                ),
                (
                    "available_start_time",
                    models.TimeField(
                        help_text="Earliest time for bookings",
                        verbose_name="Available Start Time",
                    ),
                ),
                (
                    "available_end_time",
                    models.TimeField(
                        help_text="Latest time for bookings",
                        verbose_name="Available End Time",
                    ),
                ),
                (
                    "buffer_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Buffer time between bookings in minutes",
                        verbose_name="Buffer Minutes",
                    ),
                ),
                (
                    "max_bookings_per_day",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of bookings allowed per day",
                        null=True,
                        verbose_name="Max Bookings Per Day",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this booking link is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this booking link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Link",
                "verbose_name_plural": "Booking Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Event description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("deadline", "Deadline"),
                            ("milestone", "Milestone"),
                            ("follow_up", "Follow-up"),
                            ("other", "Other"),
                        ],
                        default="meeting",
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Event start date and time", verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Event end date and time", verbose_name="End Time"
                    ),
                ),
                (
                    "all_day",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an all-day event",
                        verbose_name="All Day",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location of the event",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="Video conferencing link",
                        verbose_name="Video Link",
                    ),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True,
                        help_text="RRULE string for recurring events",
                        max_length=255,
                        verbose_name="Recurrence Rule",
                    ),
                ),
                (
                    "reminder_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Minutes before event to send reminder",
                        verbose_name="Reminder Minutes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from external calendar system",
                        max_length=255,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for the event (e.g., #FF5733)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contract associated with this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="contracts.contract",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        help_text="User who organized this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booker_name",
                    models.CharField(
                        help_text="Name of the person who made the booking",
                        max_length=255,
                        verbose_name="Booker Name",
                    ),
                ),
                (
                    "booker_email",
                    models.EmailField(
                        help_text="Email of the person who made the booking",
                        max_length=254,
                        verbose_name="Booker Email",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes from the booker",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(
                        help_text="Unique token for booking confirmation",
                        max_length=64,
                        unique=True,
                        verbose_name="Confirmation Token",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the booking was cancelled",
                        null=True,
                        verbose_name="Cancelled At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "booking_link",
                    models.ForeignKey(
                        help_text="Booking link this booking was made through",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="calendar_app.bookinglink",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        help_text="Calendar event created for this booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="calendar_app.calendarevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the attendee",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the attendee",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("tentative", "Tentative"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Response Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this attendee is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="calendar_app.calendarevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account of the attendee (if registered)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Attendee",
                "verbose_name_plural": "Event Attendees",
            },
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["organizer"], name="calendar_ap_organiz_1ff1c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["client"], name="calendar_ap_client__63e57e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["start_time"], name="calendar_ap_start_t_75262a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["status"], name="calendar_ap_status_e36391_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventattendee",
            unique_together={("event", "email")},
        ),
    ]
