# Generated by Django 5.1.4 on 2025-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='website_blo_publish_3bddab_idx',
            old_name='website_blo_publish_b5b1a1_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='website_blo_status_3bb34b_idx',
            old_name='website_blo_status_d2defd_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='website_blo_slug_3a3ea2_idx',
            old_name='website_blo_slug_a0ca10_idx',
        ),
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='website_cas_publish_2d426f_idx',
            old_name='website_cas_publish_5608d9_idx',
        ),
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='website_cas_status_c4214d_idx',
            old_name='website_cas_status_ea1907_idx',
        ),
        migrations.RenameIndex(
            model_name='casestudy',
            new_name='website_cas_slug_6a53cb_idx',
            old_name='website_cas_slug_dc5eef_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='website_con_created_48eb54_idx',
            old_name='website_con_created_5ee9ae_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='website_con_status_563f10_idx',
            old_name='website_con_status_adc398_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='website_con_email_1b8338_idx',
            old_name='website_con_email_06b940_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='website_new_email_97295a_idx',
            old_name='website_new_email_a61be7_idx',
        ),
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='website_new_status_e2c1b7_idx',
            old_name='website_new_status_1f06a0_idx',
        ),
    ]
