# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the workflow",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this workflow does",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this workflow is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("contract_signed", "Contract Signed"),
                            ("invoice_created", "Invoice Created"),
                            ("invoice_overdue", "Invoice Overdue"),
                            ("invoice_paid", "Invoice Paid"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("client_created", "Client Created"),
                            ("client_updated", "Client Updated"),
                            ("milestone_completed", "Milestone Completed"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("manual", "Manual"),
                        ],
                        help_text="Event that triggers this workflow",
                        max_length=30,
                        verbose_name="Trigger Type",
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional trigger configuration in JSON format",
                        verbose_name="Trigger Configuration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_notification", "Send Notification"),
                            ("update_client_stage", "Update Client Stage"),
                            ("create_task", "Create Task"),
                            ("create_invoice", "Create Invoice"),
                            ("webhook_call", "Webhook Call"),
                        ],
                        help_text="Type of action to perform",
                        max_length=30,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action configuration in JSON format",
                        verbose_name="Action Configuration",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Execution order of this action within the workflow",
                        verbose_name="Order",
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Delay in minutes before executing this action",
                        verbose_name="Delay (minutes)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this action is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this action belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action",
                "verbose_name_plural": "Workflow Actions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data associated with the trigger event",
                        verbose_name="Trigger Data",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the execution started",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the execution completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActionExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Current action execution status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result data from the action execution",
                        verbose_name="Result Data",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the action execution started",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the action execution completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if action execution failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        help_text="Workflow action that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflowaction",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        help_text="Parent workflow execution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_executions",
                        to="workflows.workflowexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action Execution",
                "verbose_name_plural": "Workflow Action Executions",
                "ordering": ["action__order"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["trigger_type"], name="workflows_w_trigger_278d87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["owner"], name="workflows_w_owner_i_754058_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["is_active"], name="workflows_w_is_acti_5c0b65_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowaction",
            unique_together={("workflow", "order")},
        ),
    ]
