# Generated by Django 5.1.4 on 2025-12-27 00:00

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='company', max_length=20, verbose_name='Client Type')),
                ('company_name', models.CharField(blank=True, help_text='Name of the company (if client is a company)', max_length=255, verbose_name='Company Name')),
                ('first_name', models.CharField(help_text='First name of primary contact', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of primary contact', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary phone number', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('secondary_email', models.EmailField(blank=True, help_text='Secondary email address', max_length=254, verbose_name='Secondary Email')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Secondary phone number', max_length=128, null=True, region=None, verbose_name='Secondary Phone')),
                ('website', models.URLField(blank=True, help_text='Company or personal website', verbose_name='Website')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='United States', max_length=100, verbose_name='Country')),
                ('industry', models.CharField(blank=True, help_text='Industry or business sector', max_length=100, verbose_name='Industry')),
                ('company_size', models.CharField(blank=True, help_text='Number of employees (e.g., "1-10", "11-50", etc.)', max_length=50, verbose_name='Company Size')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual revenue', max_digits=12, null=True, verbose_name='Annual Revenue')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number or VAT number', max_length=50, verbose_name='Tax ID / VAT Number')),
                ('lifecycle_stage', models.CharField(choices=[('lead', 'Lead - Initial Contact'), ('prospect', 'Prospect - Qualified Lead'), ('active', 'Active Client'), ('inactive', 'Inactive'), ('churned', 'Churned')], default='lead', help_text='Current stage in the customer lifecycle', max_length=20, verbose_name='Lifecycle Stage')),
                ('source', models.CharField(blank=True, help_text='How the client found you (e.g., "Website", "Referral", "Cold Outreach")', max_length=100, verbose_name='Lead Source')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags for categorization', size=None, verbose_name='tags')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all contracts', max_digits=12, verbose_name='Total Contract Value')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid by client', max_digits=12, verbose_name='Total Paid')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance', max_digits=12, verbose_name='Outstanding Balance')),
                ('portal_access_enabled', models.BooleanField(default=True, help_text='Whether client can access the client portal', verbose_name='Portal Access')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the client', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the client is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format', verbose_name='Metadata')),
                ('owner', models.ForeignKey(blank=True, help_text='Team member responsible for this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.OneToOneField(blank=True, help_text='User account for client portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the document', max_length=255, verbose_name='Document Name')),
                ('file', models.FileField(help_text='Document file', upload_to='clients/documents/', verbose_name='File')),
                ('file_size', models.PositiveIntegerField(editable=False, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=50, verbose_name='File Type')),
                ('description', models.TextField(blank=True, help_text='Document description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('client', models.ForeignKey(help_text='Client this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('task', 'Task/Follow-up')], default='general', max_length=50, verbose_name='Note Type')),
                ('subject', models.CharField(blank=True, help_text='Note subject or title', max_length=255, verbose_name='Subject')),
                ('content', models.TextField(help_text='Note content', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(help_text='User who created the note', on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_5a5e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clients_cli_company_58239e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['lifecycle_stage'], name='clients_cli_lifecyc_784f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['owner'], name='clients_cli_owner_i_8dadb7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_d41e6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client_type', 'company'), ('company_name__isnull', False)), models.Q(('client_type', 'individual')), _connector='OR'), name='company_name_required_for_companies'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', '-created_at'], name='clients_cli_client__5bf8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['client', '-created_at'], name='clients_cli_client__3d54e3_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['author'], name='clients_cli_author__93e7d0_idx'),
        ),
    ]
