# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Message subject",
                        max_length=255,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content", verbose_name="Content"
                    ),
                ),
                (
                    "is_from_client",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message is from the client",
                        verbose_name="From Client",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this message is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="clients.client",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent message for threading",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="clients.portalmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_portal_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Message",
                "verbose_name_plural": "Portal Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"],
                        name="clients_por_client__0182e2_idx",
                    ),
                    models.Index(
                        fields=["sender"], name="clients_por_sender__8ddd57_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="clients_por_is_read_0126bd_idx"
                    ),
                ],
            },
        ),
    ]
