# Generated by Django 5.1.4 on 2025-12-30 14:52

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='company_name_required_for_companies',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_email_56b9fc_idx',
            old_name='clients_cli_email_5a5e3d_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_company_9dfa94_idx',
            old_name='clients_cli_company_58239e_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_lifecyc_dc3d2b_idx',
            old_name='clients_cli_lifecyc_784f7b_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_owner_i_89d16e_idx',
            old_name='clients_cli_owner_i_8dadb7_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_is_acti_57c1e7_idx',
            old_name='clients_cli_is_acti_d41e6c_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='clients_cli_client__ff8b35_idx',
            old_name='clients_cli_client__5bf8ce_idx',
        ),
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='clients_cli_client__b25648_idx',
            old_name='clients_cli_client__3d54e3_idx',
        ),
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='clients_cli_author__0cc072_idx',
            old_name='clients_cli_author__93e7d0_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags for categorization', size=None),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_type', 'company'), ('company_name__isnull', False)), ('client_type', 'individual'), _connector='OR'), name='company_name_required_for_companies'),
        ),
    ]
