# Generated by Django 5.1.15 on 2026-02-07 06:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lifetime_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue from this client",
                        max_digits=12,
                        verbose_name="Lifetime Value",
                    ),
                ),
                (
                    "average_invoice_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Average Invoice Value",
                    ),
                ),
                (
                    "total_invoices",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Invoices"
                    ),
                ),
                (
                    "paid_invoices",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Paid Invoices"
                    ),
                ),
                (
                    "overdue_invoices",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Overdue Invoices"
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Outstanding Balance",
                    ),
                ),
                (
                    "total_payments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Payments"
                    ),
                ),
                (
                    "failed_payments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed Payments"
                    ),
                ),
                (
                    "total_contracts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Contracts"
                    ),
                ),
                (
                    "active_contracts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Active Contracts"
                    ),
                ),
                (
                    "last_invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Invoice Date"
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Payment Date"
                    ),
                ),
                (
                    "days_since_last_payment",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Days Since Last Payment"
                    ),
                ),
                (
                    "payment_reliability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Score 0-100 based on payment history",
                        max_digits=5,
                        verbose_name="Payment Reliability Score",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Metric",
                "verbose_name_plural": "Client Metrics",
                "ordering": ["-lifetime_value"],
            },
        ),
        migrations.CreateModel(
            name="RevenueMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Year for this metric period", verbose_name="Year"
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        help_text="Month (1-12) for this metric period",
                        verbose_name="Month",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue for the period",
                        max_digits=12,
                        verbose_name="Total Revenue",
                    ),
                ),
                (
                    "recurring_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly Recurring Revenue",
                        max_digits=12,
                        verbose_name="Recurring Revenue (MRR)",
                    ),
                ),
                (
                    "one_time_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Non-recurring revenue for the period",
                        max_digits=12,
                        verbose_name="One-Time Revenue",
                    ),
                ),
                (
                    "invoices_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Invoices Sent"
                    ),
                ),
                (
                    "invoices_paid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Invoices Paid"
                    ),
                ),
                (
                    "invoices_overdue",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Invoices Overdue"
                    ),
                ),
                (
                    "average_invoice_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Average Invoice Value",
                    ),
                ),
                (
                    "payments_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Payments Received"
                    ),
                ),
                (
                    "payments_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Payments Failed"
                    ),
                ),
                (
                    "refunds_issued",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Refunds Issued"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Refund Amount",
                    ),
                ),
                (
                    "new_clients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="New clients added this period",
                        verbose_name="New Clients",
                    ),
                ),
                (
                    "churned_clients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Clients lost this period",
                        verbose_name="Churned Clients",
                    ),
                ),
                (
                    "active_clients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total active clients at end of period",
                        verbose_name="Active Clients",
                    ),
                ),
                (
                    "contracts_signed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contracts Signed"
                    ),
                ),
                (
                    "contracts_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contracts Completed"
                    ),
                ),
                (
                    "active_contracts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Active Contracts"
                    ),
                ),
                (
                    "total_contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Contract Value",
                    ),
                ),
                (
                    "payment_success_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of successful payments",
                        max_digits=5,
                        verbose_name="Payment Success Rate",
                    ),
                ),
                (
                    "churn_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Client churn rate percentage",
                        max_digits=5,
                        verbose_name="Churn Rate",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When these metrics were last calculated",
                        verbose_name="Calculated At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Revenue Metric",
                "verbose_name_plural": "Revenue Metrics",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["-year", "-month"], name="analytics_r_year_f43ee4_idx"
                    )
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "Invoice Created"),
                            ("invoice_sent", "Invoice Sent"),
                            ("invoice_paid", "Invoice Paid"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("contract_signed", "Contract Signed"),
                            ("contract_completed", "Contract Completed"),
                            ("client_created", "Client Created"),
                            ("client_updated", "Client Updated"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                        ],
                        max_length=50,
                        verbose_name="Activity Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable description of the activity",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "related_objects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="IDs and types of related objects",
                        verbose_name="Related Objects",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional activity data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analytics_a_created_b5efc6_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_a_user_id_abe786_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="analytics_a_activit_c99d4e_idx",
                    ),
                ],
            },
        ),
    ]
