# Generated by Django 5.1.4 on 2025-12-30 14:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('clients', '0002_remove_client_company_name_required_for_companies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='analytics_a_activit_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='analytics_a_created_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='related_object_type',
        ),
        migrations.RemoveField(
            model_name='clientmetric',
            name='average_days_to_pay',
        ),
        migrations.RemoveField(
            model_name='revenuemetric',
            name='outstanding_balance',
        ),
        migrations.RemoveField(
            model_name='revenuemetric',
            name='overdue_amount',
        ),
        migrations.RemoveField(
            model_name='revenuemetric',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clientmetric',
            name='average_invoice_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Average Invoice Value'),
        ),
        migrations.AddField(
            model_name='clientmetric',
            name='last_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Invoice Date'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='active_contracts',
            field=models.PositiveIntegerField(default=0, verbose_name='Active Contracts'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True, help_text='When these metrics were last calculated', verbose_name='Calculated At'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='contracts_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Contracts Completed'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='contracts_signed',
            field=models.PositiveIntegerField(default=0, verbose_name='Contracts Signed'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='invoices_overdue',
            field=models.PositiveIntegerField(default=0, verbose_name='Invoices Overdue'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='payments_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='Payments Failed'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='payments_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Payments Received'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund Amount'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='refunds_issued',
            field=models.PositiveIntegerField(default=0, verbose_name='Refunds Issued'),
        ),
        migrations.AddField(
            model_name='revenuemetric',
            name='total_contract_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Contract Value'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('contract_signed', 'Contract Signed'), ('contract_completed', 'Contract Completed'), ('client_created', 'Client Created'), ('client_updated', 'Client Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=50, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.CharField(help_text='Human-readable description of the activity', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional activity data', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='related_objects',
            field=models.JSONField(blank=True, default=dict, help_text='IDs and types of related objects', verbose_name='Related Objects'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='active_contracts',
            field=models.PositiveIntegerField(default=0, verbose_name='Active Contracts'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='days_since_last_payment',
            field=models.PositiveIntegerField(default=0, verbose_name='Days Since Last Payment'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='failed_payments',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Payments'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Outstanding Balance'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='overdue_invoices',
            field=models.PositiveIntegerField(default=0, verbose_name='Overdue Invoices'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='paid_invoices',
            field=models.PositiveIntegerField(default=0, verbose_name='Paid Invoices'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='payment_reliability_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score 0-100 based on payment history', max_digits=5, verbose_name='Payment Reliability Score'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='total_contracts',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Contracts'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='total_invoices',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Invoices'),
        ),
        migrations.AlterField(
            model_name='clientmetric',
            name='total_payments',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Payments'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='active_clients',
            field=models.PositiveIntegerField(default=0, help_text='Total active clients at end of period', verbose_name='Active Clients'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='average_invoice_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Average Invoice Value'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='invoices_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Invoices Paid'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='invoices_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='Invoices Sent'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='new_clients',
            field=models.PositiveIntegerField(default=0, help_text='New clients added this period', verbose_name='New Clients'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='one_time_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-recurring revenue for the period', max_digits=12, verbose_name='One-Time Revenue'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='recurring_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly Recurring Revenue', max_digits=12, verbose_name='Recurring Revenue (MRR)'),
        ),
        migrations.AlterField(
            model_name='revenuemetric',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue for the period', max_digits=12, verbose_name='Total Revenue'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='analytics_a_created_b5efc6_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_abe786_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', '-created_at'], name='analytics_a_activit_c99d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuemetric',
            index=models.Index(fields=['-year', '-month'], name='analytics_r_year_f43ee4_idx'),
        ),
    ]
