"""
AI Assistant models for suggestions, cash flow predictions, and insights.
"""

import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class AISuggestion(models.Model):
    """
    AI-powered suggestion for user actions.

    Represents actionable recommendations generated by AI analysis
    of user data, such as follow-up reminders, invoice reminders,
    and contract drafting suggestions.
    """

    # Suggestion Types
    FOLLOW_UP = 'follow_up'
    CONTRACT_DRAFT = 'contract_draft'
    INVOICE_REMINDER = 'invoice_reminder'
    CASH_FLOW = 'cash_flow'
    CLIENT_INSIGHT = 'client_insight'
    PRICING = 'pricing'

    SUGGESTION_TYPE_CHOICES = [
        (FOLLOW_UP, _('Follow Up')),
        (CONTRACT_DRAFT, _('Contract Draft')),
        (INVOICE_REMINDER, _('Invoice Reminder')),
        (CASH_FLOW, _('Cash Flow')),
        (CLIENT_INSIGHT, _('Client Insight')),
        (PRICING, _('Pricing')),
    ]

    # Priority Levels
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    PRIORITY_CHOICES = [
        (LOW, _('Low')),
        (MEDIUM, _('Medium')),
        (HIGH, _('High')),
    ]

    # Status
    PENDING = 'pending'
    ACCEPTED = 'accepted'
    DISMISSED = 'dismissed'
    EXPIRED = 'expired'

    STATUS_CHOICES = [
        (PENDING, _('Pending')),
        (ACCEPTED, _('Accepted')),
        (DISMISSED, _('Dismissed')),
        (EXPIRED, _('Expired')),
    ]

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    suggestion_type = models.CharField(
        _('Suggestion Type'),
        max_length=20,
        choices=SUGGESTION_TYPE_CHOICES
    )

    title = models.CharField(
        _('Title'),
        max_length=255,
        help_text=_('Brief title for the suggestion')
    )

    description = models.TextField(
        _('Description'),
        help_text=_('Detailed description of the suggestion')
    )

    detail = models.JSONField(
        _('Detail'),
        default=dict,
        blank=True,
        help_text=_('Additional detail data in JSON format')
    )

    priority = models.CharField(
        _('Priority'),
        max_length=10,
        choices=PRIORITY_CHOICES,
        default=MEDIUM
    )

    status = models.CharField(
        _('Status'),
        max_length=10,
        choices=STATUS_CHOICES,
        default=PENDING
    )

    # Relationships
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
        related_name='ai_suggestions',
        help_text=_('User this suggestion is for')
    )

    client = models.ForeignKey(
        'clients.Client',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_suggestions',
        help_text=_('Related client (if applicable)')
    )

    contract = models.ForeignKey(
        'contracts.Contract',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_suggestions',
        help_text=_('Related contract (if applicable)')
    )

    invoice = models.ForeignKey(
        'invoicing.Invoice',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='ai_suggestions',
        help_text=_('Related invoice (if applicable)')
    )

    # Timing
    expires_at = models.DateTimeField(
        _('Expires At'),
        null=True,
        blank=True,
        help_text=_('When this suggestion expires')
    )

    accepted_at = models.DateTimeField(
        _('Accepted At'),
        null=True,
        blank=True,
        help_text=_('When the suggestion was accepted')
    )

    dismissed_at = models.DateTimeField(
        _('Dismissed At'),
        null=True,
        blank=True,
        help_text=_('When the suggestion was dismissed')
    )

    # Metadata
    metadata = models.JSONField(
        _('Metadata'),
        default=dict,
        blank=True,
        help_text=_('Additional metadata in JSON format')
    )

    # Timestamps
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    class Meta:
        verbose_name = _('AI Suggestion')
        verbose_name_plural = _('AI Suggestions')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['suggestion_type']),
            models.Index(fields=['status']),
            models.Index(fields=['priority']),
        ]

    def __str__(self):
        return f"{self.title} ({self.suggestion_type})"

    @property
    def is_expired(self):
        """Check if the suggestion has expired."""
        if self.expires_at and self.status == self.PENDING:
            return self.expires_at < timezone.now()
        return False


class CashFlowPrediction(models.Model):
    """
    AI-generated cash flow prediction.

    Stores predicted income and expenses for a specific date,
    along with confidence scores and actual values for accuracy tracking.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    prediction_date = models.DateField(
        _('Prediction Date'),
        help_text=_('Date this prediction is for')
    )

    predicted_income = models.DecimalField(
        _('Predicted Income'),
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text=_('Predicted income for the date')
    )

    predicted_expenses = models.DecimalField(
        _('Predicted Expenses'),
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text=_('Predicted expenses for the date')
    )

    predicted_net = models.DecimalField(
        _('Predicted Net'),
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text=_('Predicted net cash flow (income - expenses)')
    )

    confidence_score = models.DecimalField(
        _('Confidence Score'),
        max_digits=3,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(1)],
        help_text=_('Confidence score between 0 and 1')
    )

    actual_income = models.DecimalField(
        _('Actual Income'),
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_('Actual income for the date (filled after the fact)')
    )

    actual_expenses = models.DecimalField(
        _('Actual Expenses'),
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_('Actual expenses for the date (filled after the fact)')
    )

    factors = models.JSONField(
        _('Factors'),
        default=list,
        blank=True,
        help_text=_('Factors contributing to this prediction')
    )

    # Relationships
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
        related_name='cash_flow_predictions',
        help_text=_('User this prediction belongs to')
    )

    # Timestamps
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    class Meta:
        verbose_name = _('Cash Flow Prediction')
        verbose_name_plural = _('Cash Flow Predictions')
        ordering = ['-prediction_date']
        unique_together = [['user', 'prediction_date']]

    def __str__(self):
        return f"Prediction for {self.prediction_date}: net {self.predicted_net}"

    @property
    def actual_net(self):
        """Calculate actual net cash flow if both actuals are available."""
        if self.actual_income is not None and self.actual_expenses is not None:
            return self.actual_income - self.actual_expenses
        return None

    @property
    def accuracy(self):
        """
        Calculate prediction accuracy.

        Returns a value between 0 and 1 representing how accurate
        the prediction was compared to actual values.
        """
        actual = self.actual_net
        if actual is not None and actual != 0:
            return 1 - abs(self.predicted_net - actual) / abs(actual)
        return None


class AIInsight(models.Model):
    """
    AI-generated insight about user's business.

    Represents analytical observations such as revenue trends,
    client risk assessments, and payment patterns.
    """

    # Insight Types
    REVENUE_TREND = 'revenue_trend'
    CLIENT_RISK = 'client_risk'
    PAYMENT_PATTERN = 'payment_pattern'
    SEASONAL = 'seasonal'
    GROWTH = 'growth'

    INSIGHT_TYPE_CHOICES = [
        (REVENUE_TREND, _('Revenue Trend')),
        (CLIENT_RISK, _('Client Risk')),
        (PAYMENT_PATTERN, _('Payment Pattern')),
        (SEASONAL, _('Seasonal')),
        (GROWTH, _('Growth')),
    ]

    # Severity Levels
    INFO = 'info'
    WARNING = 'warning'
    CRITICAL = 'critical'

    SEVERITY_CHOICES = [
        (INFO, _('Info')),
        (WARNING, _('Warning')),
        (CRITICAL, _('Critical')),
    ]

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    insight_type = models.CharField(
        _('Insight Type'),
        max_length=20,
        choices=INSIGHT_TYPE_CHOICES
    )

    title = models.CharField(
        _('Title'),
        max_length=255,
        help_text=_('Brief title for the insight')
    )

    description = models.TextField(
        _('Description'),
        help_text=_('Detailed description of the insight')
    )

    data = models.JSONField(
        _('Data'),
        default=dict,
        blank=True,
        help_text=_('Supporting data for the insight in JSON format')
    )

    severity = models.CharField(
        _('Severity'),
        max_length=10,
        choices=SEVERITY_CHOICES,
        default=INFO
    )

    # Relationships
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
        related_name='ai_insights',
        help_text=_('User this insight is for')
    )

    # Read tracking
    is_read = models.BooleanField(
        _('Is Read'),
        default=False,
        help_text=_('Whether the user has read this insight')
    )

    read_at = models.DateTimeField(
        _('Read At'),
        null=True,
        blank=True,
        help_text=_('When the insight was read')
    )

    # Timestamps
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    class Meta:
        verbose_name = _('AI Insight')
        verbose_name_plural = _('AI Insights')
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['insight_type']),
            models.Index(fields=['severity']),
            models.Index(fields=['is_read']),
        ]

    def __str__(self):
        return f"{self.title} ({self.severity})"

    def mark_as_read(self):
        """Mark the insight as read."""
        self.is_read = True
        self.read_at = timezone.now()
        self.save()
