# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("revenue_trend", "Revenue Trend"),
                            ("client_risk", "Client Risk"),
                            ("payment_pattern", "Payment Pattern"),
                            ("seasonal", "Seasonal"),
                            ("growth", "Growth"),
                        ],
                        max_length=20,
                        verbose_name="Insight Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the insight",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the insight",
                        verbose_name="Description",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting data for the insight in JSON format",
                        verbose_name="Data",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has read this insight",
                        verbose_name="Is Read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the insight was read",
                        null=True,
                        verbose_name="Read At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this insight is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Insight",
                "verbose_name_plural": "AI Insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="ai_assistan_user_id_8d8fab_idx"
                    ),
                    models.Index(
                        fields=["insight_type"], name="ai_assistan_insight_627157_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="ai_assistan_severit_96865b_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="ai_assistan_is_read_05d07a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("follow_up", "Follow Up"),
                            ("contract_draft", "Contract Draft"),
                            ("invoice_reminder", "Invoice Reminder"),
                            ("cash_flow", "Cash Flow"),
                            ("client_insight", "Client Insight"),
                            ("pricing", "Pricing"),
                        ],
                        max_length=20,
                        verbose_name="Suggestion Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the suggestion",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the suggestion",
                        verbose_name="Description",
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional detail data in JSON format",
                        verbose_name="Detail",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this suggestion expires",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the suggestion was accepted",
                        null=True,
                        verbose_name="Accepted At",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the suggestion was dismissed",
                        null=True,
                        verbose_name="Dismissed At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related client (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related contract (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related invoice (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this suggestion is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Suggestion",
                "verbose_name_plural": "AI Suggestions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="ai_assistan_user_id_003d00_idx"
                    ),
                    models.Index(
                        fields=["suggestion_type"],
                        name="ai_assistan_suggest_51e100_idx",
                    ),
                    models.Index(
                        fields=["status"], name="ai_assistan_status_83e26b_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="ai_assistan_priorit_2b9bfb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CashFlowPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(
                        help_text="Date this prediction is for",
                        verbose_name="Prediction Date",
                    ),
                ),
                (
                    "predicted_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Predicted income for the date",
                        max_digits=12,
                        verbose_name="Predicted Income",
                    ),
                ),
                (
                    "predicted_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Predicted expenses for the date",
                        max_digits=12,
                        verbose_name="Predicted Expenses",
                    ),
                ),
                (
                    "predicted_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Predicted net cash flow (income - expenses)",
                        max_digits=12,
                        verbose_name="Predicted Net",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confidence score between 0 and 1",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "actual_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual income for the date (filled after the fact)",
                        max_digits=12,
                        null=True,
                        verbose_name="Actual Income",
                    ),
                ),
                (
                    "actual_expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual expenses for the date (filled after the fact)",
                        max_digits=12,
                        null=True,
                        verbose_name="Actual Expenses",
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Factors contributing to this prediction",
                        verbose_name="Factors",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this prediction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Prediction",
                "verbose_name_plural": "Cash Flow Predictions",
                "ordering": ["-prediction_date"],
                "unique_together": {("user", "prediction_date")},
            },
        ),
    ]
