# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Category description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code (e.g., #FF5733)",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is currently active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description of the expense",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        help_text="Date the expense was incurred",
                        verbose_name="Expense Date",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense is billable to a client",
                        verbose_name="Billable",
                    ),
                ),
                (
                    "is_invoiced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this expense has been invoiced",
                        verbose_name="Invoiced",
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded receipt file",
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Receipt File",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt or reference number",
                        max_length=100,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor or merchant name",
                        max_length=255,
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        default="card",
                        help_text="Method of payment used",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invoiced", "Invoiced"),
                        ],
                        default="pending",
                        help_text="Current expense status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the expense was approved",
                        null=True,
                        verbose_name="Approved At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the expense",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the expense",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated client (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contract (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="contracts.contract",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated invoice (if invoiced)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="User who submitted the expense",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="expenses_ex_categor_20264a_idx"
                    ),
                    models.Index(
                        fields=["client"], name="expenses_ex_client__2ce088_idx"
                    ),
                    models.Index(
                        fields=["status"], name="expenses_ex_status_cbb790_idx"
                    ),
                    models.Index(
                        fields=["submitted_by"], name="expenses_ex_submitt_3b4604_idx"
                    ),
                    models.Index(
                        fields=["expense_date"], name="expenses_ex_expense_cf8a73_idx"
                    ),
                ],
            },
        ),
    ]
