# Generated by Django 5.1.4 on 2026-02-13 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_portalmessage"),
        ("contracts", "0001_initial"),
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address for this account",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name shown in sent emails",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("gmail", "Gmail"),
                            ("outlook", "Outlook"),
                            ("ses", "SES"),
                        ],
                        default="smtp",
                        help_text="Email service provider",
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration (SMTP settings, API keys, etc.)",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this email account is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default email account for the user",
                        verbose_name="Default",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this email account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "ordering": ["-is_default", "-created_at"],
                "unique_together": {("user", "email_address")},
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        help_text="Whether the email is inbound or outbound",
                        max_length=20,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        help_text="Sender email address",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "to_emails",
                    models.JSONField(
                        default=list,
                        help_text="List of recipient email addresses",
                        verbose_name="To Emails",
                    ),
                ),
                (
                    "cc_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of CC email addresses",
                        verbose_name="CC Emails",
                    ),
                ),
                (
                    "bcc_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of BCC email addresses",
                        verbose_name="BCC Emails",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line",
                        max_length=500,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text email body",
                        verbose_name="Body (Text)",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML email body",
                        verbose_name="Body (HTML)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                        ],
                        default="draft",
                        help_text="Current status of the email",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        help_text="Email Message-ID header",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Message-ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Thread identifier for grouping related emails",
                        max_length=255,
                        verbose_name="Thread ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email has been read",
                        verbose_name="Read",
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was first opened by the recipient",
                        null=True,
                        verbose_name="Opened At",
                    ),
                ),
                (
                    "opened_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times the email was opened",
                        verbose_name="Opened Count",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was sent",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was received",
                        null=True,
                        verbose_name="Received At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Email account used for this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="emails.emailaccount",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated client",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_messages",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_messages",
                        to="contracts.contract",
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Email this is a reply to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="emails.emailmessage",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_messages",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file",
                        upload_to="emails/attachments/",
                        verbose_name="File",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original file name",
                        max_length=255,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="File Size",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        help_text="Email message this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.emailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the email template",
                        max_length=255,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line template",
                        max_length=500,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text email body template",
                        verbose_name="Body (Text)",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML email body template",
                        verbose_name="Body (HTML)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("follow_up", "Follow-up"),
                            ("invoice", "Invoice"),
                            ("contract", "Contract"),
                            ("reminder", "Reminder"),
                            ("welcome", "Welcome"),
                        ],
                        default="general",
                        help_text="Template category",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of variable names available for substitution",
                        verbose_name="Available Variables",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["account"], name="emails_emai_account_9d88e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(fields=["status"], name="emails_emai_status_bbf48a_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["client"], name="emails_emai_client__b79791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["thread_id"], name="emails_emai_thread__78be32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["direction"], name="emails_emai_directi_232e93_idx"
            ),
        ),
    ]
