# Generated by Django 5.1.4 on 2025-12-30 14:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_contracts_c_contrac_18f6c0_idx_contracts_c_contrac_876f48_idx_and_more'),
        ('invoicing', '0002_rename_invoicing_i_invoice_e7b0b8_idx_invoicing_i_invoice_f2b05e_idx_and_more'),
        ('notifications', '0001_initial'),
        ('payments', '0002_rename_payments_pa_invoice_4b5568_idx_payments_pa_invoice_fcb1dc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_d92267_idx',
            old_name='notificatio_status_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], default='email', max_length=20, verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from email/SMS provider', max_length=255, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Failed At'),
        ),
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for notification (if not to a user)', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_html',
            field=models.TextField(blank=True, help_text='HTML message content', verbose_name='Message (HTML)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_text',
            field=models.TextField(help_text='Plain text message content', verbose_name='Message (Plain Text)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='invoicing.invoice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User receiving this notification (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='available_variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of available template variables', size=None, verbose_name='Available Variables'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification')], default='email', max_length=20, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='send_to_client',
            field=models.BooleanField(default=True, help_text='Send this notification to the client', verbose_name='Send to Client'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='send_to_owner',
            field=models.BooleanField(default=False, help_text='Send this notification to the contract/invoice owner', verbose_name='Send to Owner'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email', '-created_at'], name='notificatio_email_8cf883_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
    ]
